### PR TITLE
Sompy samplename fix

### PR DESCRIPTION
**Pull request by Aisha-D**
- Get the sample name from the input file
- Raise error if output argument file input file is not found

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/multiqc_plugins/1)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/multiqc_plugins/1)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[`seglh_plugin/modules/sompy/sompy.py` line 225 at r1](https://reviewable.io/reviews/eastgenomics/multiqc_plugins/1#-N6NdpQNEmgHse2m1jmN:-N6NdpQNEmgHse2m1jmO:b20drql) ([raw file](https://github.com/eastgenomics/multiqc_plugins/blob/c0fa3f0490ab3d221c0259f012e5dbfae3e254d5/seglh_plugin/modules/sompy/sompy.py#L225)):*
> ```Python
>                 # get sample identifier from output name
>                 sample_name = None
>                 m = re.search(r'.*-o\s*(\S+)', data['sompycmd'])
> ```

what is this meant to be matching? a comment with an example would be good pls
___
*[`seglh_plugin/modules/sompy/sompy.py` line 226 at r1](https://reviewable.io/reviews/eastgenomics/multiqc_plugins/1#-N6NdtXF4DssSIwpY9Hb:-N6NdtXF4DssSIwpY9Hc:bb6bhmv) ([raw file](https://github.com/eastgenomics/multiqc_plugins/blob/c0fa3f0490ab3d221c0259f012e5dbfae3e254d5/seglh_plugin/modules/sompy/sompy.py#L226)):*
> ```Python
>                 sample_name = None
>                 m = re.search(r'.*-o\s*(\S+)', data['sompycmd'])
>                 if m:
> ```

single character variable, `match` or similar would be better (then it is `if match:` which is nice and enjoyable to read)
___
*[`seglh_plugin/modules/sompy/sompy.py` line 227 at r1](https://reviewable.io/reviews/eastgenomics/multiqc_plugins/1#-N6NeOyJ5Hov0UgGKbUi:-N6NeOyKApwZFsoycd_X:bsj0y8v) ([raw file](https://github.com/eastgenomics/multiqc_plugins/blob/c0fa3f0490ab3d221c0259f012e5dbfae3e254d5/seglh_plugin/modules/sompy/sompy.py#L227)):*
> ```Python
>                 m = re.search(r'.*-o\s*(\S+)', data['sompycmd'])
>                 if m:
>                     sample_name = os.path.basename(m.group(1))
> ```

incase you aren't aware there's also `Path` from `pathlib` for working with paths: https://docs.python.org/3/library/pathlib.html

but `os.path.basename` is fine too :)

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/multiqc_plugins/1)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`seglh_plugin/modules/sompy/sompy.py` line 225 at r1](https://reviewable.io/reviews/eastgenomics/multiqc_plugins/1#-N6NdpQNEmgHse2m1jmN:-N6NjXWd8zcJULo6Ye3H:b-9xc2d4) ([raw file](https://github.com/eastgenomics/multiqc_plugins/blob/c0fa3f0490ab3d221c0259f012e5dbfae3e254d5/seglh_plugin/modules/sompy/sompy.py#L225)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what is this meant to be matching? a comment with an example would be good pls
</blockquote></details>

In the file it contains the command line code used to run sompy, in it contains the output argument. A screenshot example:

___
*[`seglh_plugin/modules/sompy/sompy.py` line 226 at r1](https://reviewable.io/reviews/eastgenomics/multiqc_plugins/1#-N6NdtXF4DssSIwpY9Hb:-N6NkdlXDUXPx_4e0G4D:b-896fix) ([raw file](https://github.com/eastgenomics/multiqc_plugins/blob/c0fa3f0490ab3d221c0259f012e5dbfae3e254d5/seglh_plugin/modules/sompy/sompy.py#L226)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

single character variable, `match` or similar would be better (then it is `if match:` which is nice and enjoyable to read)
</blockquote></details>

Done.
___
*[`seglh_plugin/modules/sompy/sompy.py` line 227 at r1](https://reviewable.io/reviews/eastgenomics/multiqc_plugins/1#-N6NeOyJ5Hov0UgGKbUi:-N6Nke6B-WTAC5_EjRJT:bul9mdj) ([raw file](https://github.com/eastgenomics/multiqc_plugins/blob/c0fa3f0490ab3d221c0259f012e5dbfae3e254d5/seglh_plugin/modules/sompy/sompy.py#L227)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

incase you aren't aware there's also `Path` from `pathlib` for working with paths: https://docs.python.org/3/library/pathlib.html

but `os.path.basename` is fine too :)
</blockquote></details>

this was the original code

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/multiqc_plugins/1)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Aisha-D and @jethror1)

___
*[`seglh_plugin/modules/sompy/sompy.py` line 225 at r1](https://reviewable.io/reviews/eastgenomics/multiqc_plugins/1#-N6NdpQNEmgHse2m1jmN:-N6Nmc8bEp4MZrIPKuv4:b-acuivb) ([raw file](https://github.com/eastgenomics/multiqc_plugins/blob/c0fa3f0490ab3d221c0259f012e5dbfae3e254d5/seglh_plugin/modules/sompy/sompy.py#L225)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

In the file it contains the command line code used to run sompy, in it contains the output argument. A screenshot example:


</blockquote></details>

ahhh makes sense can you add a comment something like `# matches for -o {output file} in command string` to parse out sample name from, regex on its own is hard



_Code quote:_
```Python
.*-o\s*(\S+)
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/multiqc_plugins/1)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`seglh_plugin/modules/sompy/sompy.py` line 225 at r1](https://reviewable.io/reviews/eastgenomics/multiqc_plugins/1#-N6NdpQNEmgHse2m1jmN:-N6NqbwMEMowfhUFd81g:b-896fix) ([raw file](https://github.com/eastgenomics/multiqc_plugins/blob/c0fa3f0490ab3d221c0259f012e5dbfae3e254d5/seglh_plugin/modules/sompy/sompy.py#L225)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ahhh makes sense can you add a comment something like `# matches for -o {output file} in command string` to parse out sample name from, regex on its own is hard
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/multiqc_plugins/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
